export const HCPCS_CATEGORY_COLORS: Record<string, string> = {
  'E&M': '#2563eb',
  'Surgery': '#dc2626',
  'Radiology': '#7c3aed',
  'Pathology/Lab': '#0891b2',
  'Medicine': '#16a34a',
  'State Medicaid': '#ea580c',
  'Drugs': '#db2777',
  'Behavioral Health': '#9333ea',
  'DME': '#ca8a04',
  'Dental': '#059669',
  'Procedures/Services': '#4f46e5',
  'Transport & DME': '#b45309',
  'Orthotics/Prosthetics': '#0d9488',
  'Vision/Hearing': '#6366f1',
  'Outpatient Hospital': '#e11d48',
  'Enteral/Parenteral': '#65a30d',
  'Private Payer': '#a855f7',
  'Quality Measures': '#64748b',
  'Temporary Codes': '#78716c',
  'Other Level II': '#94a3b8',
  'Other': '#475569',
};

export const HCPCS_CATEGORY_ORDER = [
  'State Medicaid',
  'Drugs',
  'E&M',
  'Surgery',
  'Medicine',
  'Behavioral Health',
  'DME',
  'Pathology/Lab',
  'Radiology',
  'Procedures/Services',
  'Dental',
  'Orthotics/Prosthetics',
  'Transport & DME',
  'Vision/Hearing',
  'Outpatient Hospital',
  'Enteral/Parenteral',
  'Private Payer',
  'Quality Measures',
  'Temporary Codes',
  'Other Level II',
  'Other',
];
